namespace WebApp.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ds : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.BaseCodes", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.BaseCodes", "LastModifiedDate", c => c.DateTime());
            AddColumn("dbo.CodeItems", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.CodeItems", "LastModifiedDate", c => c.DateTime());
            AddColumn("dbo.Categories", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Categories", "LastModifiedDate", c => c.DateTime());
            AddColumn("dbo.Products", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Products", "LastModifiedDate", c => c.DateTime());
            AddColumn("dbo.Companies", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Companies", "LastModifiedDate", c => c.DateTime());
            AddColumn("dbo.Departments", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Departments", "LastModifiedDate", c => c.DateTime());
            AddColumn("dbo.Employees", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Employees", "LastModifiedDate", c => c.DateTime());
            AddColumn("dbo.DataTableImportMappings", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.DataTableImportMappings", "LastModifiedDate", c => c.DateTime());
            AddColumn("dbo.MenuItems", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.MenuItems", "LastModifiedDate", c => c.DateTime());
            AddColumn("dbo.Messages", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Messages", "LastModifiedDate", c => c.DateTime());
            AddColumn("dbo.Notifications", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Notifications", "LastModifiedDate", c => c.DateTime());
            AddColumn("dbo.OrderDetails", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.OrderDetails", "LastModifiedDate", c => c.DateTime());
            AddColumn("dbo.Orders", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Orders", "LastModifiedDate", c => c.DateTime());
            AddColumn("dbo.RoleMenus", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.RoleMenus", "LastModifiedDate", c => c.DateTime());
            AddColumn("dbo.Works", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Works", "LastModifiedDate", c => c.DateTime());
            AlterColumn("dbo.BaseCodes", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.BaseCodes", "LastModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.CodeItems", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.CodeItems", "LastModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Categories", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Categories", "LastModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Products", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Products", "LastModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Companies", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Companies", "LastModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Departments", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Departments", "LastModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Employees", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Employees", "LastModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.DataTableImportMappings", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.DataTableImportMappings", "LastModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.MenuItems", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.MenuItems", "LastModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Messages", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Messages", "LastModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Notifications", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Notifications", "LastModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.OrderDetails", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.OrderDetails", "LastModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Orders", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Orders", "LastModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.RoleMenus", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.RoleMenus", "LastModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Works", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.Works", "LastModifiedBy", c => c.String(maxLength: 20));
            DropColumn("dbo.BaseCodes", "Created");
            DropColumn("dbo.BaseCodes", "LastModified");
            DropColumn("dbo.CodeItems", "Created");
            DropColumn("dbo.CodeItems", "LastModified");
            DropColumn("dbo.Categories", "Created");
            DropColumn("dbo.Categories", "LastModified");
            DropColumn("dbo.Products", "Created");
            DropColumn("dbo.Products", "LastModified");
            DropColumn("dbo.Companies", "Created");
            DropColumn("dbo.Companies", "LastModified");
            DropColumn("dbo.Departments", "Created");
            DropColumn("dbo.Departments", "LastModified");
            DropColumn("dbo.Employees", "Created");
            DropColumn("dbo.Employees", "LastModified");
            DropColumn("dbo.DataTableImportMappings", "Created");
            DropColumn("dbo.DataTableImportMappings", "LastModified");
            DropColumn("dbo.MenuItems", "Created");
            DropColumn("dbo.MenuItems", "LastModified");
            DropColumn("dbo.Messages", "LastModified");
            DropColumn("dbo.Notifications", "LastModified");
            DropColumn("dbo.OrderDetails", "Created");
            DropColumn("dbo.OrderDetails", "LastModified");
            DropColumn("dbo.Orders", "Created");
            DropColumn("dbo.Orders", "LastModified");
            DropColumn("dbo.RoleMenus", "Created");
            DropColumn("dbo.RoleMenus", "LastModified");
            DropColumn("dbo.Works", "Created");
            DropColumn("dbo.Works", "LastModified");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Works", "LastModified", c => c.DateTime());
            AddColumn("dbo.Works", "Created", c => c.DateTime());
            AddColumn("dbo.RoleMenus", "LastModified", c => c.DateTime());
            AddColumn("dbo.RoleMenus", "Created", c => c.DateTime());
            AddColumn("dbo.Orders", "LastModified", c => c.DateTime());
            AddColumn("dbo.Orders", "Created", c => c.DateTime());
            AddColumn("dbo.OrderDetails", "LastModified", c => c.DateTime());
            AddColumn("dbo.OrderDetails", "Created", c => c.DateTime());
            AddColumn("dbo.Notifications", "LastModified", c => c.DateTime());
            AddColumn("dbo.Messages", "LastModified", c => c.DateTime());
            AddColumn("dbo.MenuItems", "LastModified", c => c.DateTime());
            AddColumn("dbo.MenuItems", "Created", c => c.DateTime());
            AddColumn("dbo.DataTableImportMappings", "LastModified", c => c.DateTime());
            AddColumn("dbo.DataTableImportMappings", "Created", c => c.DateTime());
            AddColumn("dbo.Employees", "LastModified", c => c.DateTime());
            AddColumn("dbo.Employees", "Created", c => c.DateTime());
            AddColumn("dbo.Departments", "LastModified", c => c.DateTime());
            AddColumn("dbo.Departments", "Created", c => c.DateTime());
            AddColumn("dbo.Companies", "LastModified", c => c.DateTime());
            AddColumn("dbo.Companies", "Created", c => c.DateTime());
            AddColumn("dbo.Products", "LastModified", c => c.DateTime());
            AddColumn("dbo.Products", "Created", c => c.DateTime());
            AddColumn("dbo.Categories", "LastModified", c => c.DateTime());
            AddColumn("dbo.Categories", "Created", c => c.DateTime());
            AddColumn("dbo.CodeItems", "LastModified", c => c.DateTime());
            AddColumn("dbo.CodeItems", "Created", c => c.DateTime());
            AddColumn("dbo.BaseCodes", "LastModified", c => c.DateTime());
            AddColumn("dbo.BaseCodes", "Created", c => c.DateTime());
            AlterColumn("dbo.Works", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.Works", "CreatedBy", c => c.String());
            AlterColumn("dbo.RoleMenus", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.RoleMenus", "CreatedBy", c => c.String());
            AlterColumn("dbo.Orders", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.Orders", "CreatedBy", c => c.String());
            AlterColumn("dbo.OrderDetails", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.OrderDetails", "CreatedBy", c => c.String());
            AlterColumn("dbo.Notifications", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.Notifications", "CreatedBy", c => c.String());
            AlterColumn("dbo.Messages", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.Messages", "CreatedBy", c => c.String());
            AlterColumn("dbo.MenuItems", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.MenuItems", "CreatedBy", c => c.String());
            AlterColumn("dbo.DataTableImportMappings", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.DataTableImportMappings", "CreatedBy", c => c.String());
            AlterColumn("dbo.Employees", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.Employees", "CreatedBy", c => c.String());
            AlterColumn("dbo.Departments", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.Departments", "CreatedBy", c => c.String());
            AlterColumn("dbo.Companies", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.Companies", "CreatedBy", c => c.String());
            AlterColumn("dbo.Products", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.Products", "CreatedBy", c => c.String());
            AlterColumn("dbo.Categories", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.Categories", "CreatedBy", c => c.String());
            AlterColumn("dbo.CodeItems", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.CodeItems", "CreatedBy", c => c.String());
            AlterColumn("dbo.BaseCodes", "LastModifiedBy", c => c.String());
            AlterColumn("dbo.BaseCodes", "CreatedBy", c => c.String());
            DropColumn("dbo.Works", "LastModifiedDate");
            DropColumn("dbo.Works", "CreatedDate");
            DropColumn("dbo.RoleMenus", "LastModifiedDate");
            DropColumn("dbo.RoleMenus", "CreatedDate");
            DropColumn("dbo.Orders", "LastModifiedDate");
            DropColumn("dbo.Orders", "CreatedDate");
            DropColumn("dbo.OrderDetails", "LastModifiedDate");
            DropColumn("dbo.OrderDetails", "CreatedDate");
            DropColumn("dbo.Notifications", "LastModifiedDate");
            DropColumn("dbo.Notifications", "CreatedDate");
            DropColumn("dbo.Messages", "LastModifiedDate");
            DropColumn("dbo.Messages", "CreatedDate");
            DropColumn("dbo.MenuItems", "LastModifiedDate");
            DropColumn("dbo.MenuItems", "CreatedDate");
            DropColumn("dbo.DataTableImportMappings", "LastModifiedDate");
            DropColumn("dbo.DataTableImportMappings", "CreatedDate");
            DropColumn("dbo.Employees", "LastModifiedDate");
            DropColumn("dbo.Employees", "CreatedDate");
            DropColumn("dbo.Departments", "LastModifiedDate");
            DropColumn("dbo.Departments", "CreatedDate");
            DropColumn("dbo.Companies", "LastModifiedDate");
            DropColumn("dbo.Companies", "CreatedDate");
            DropColumn("dbo.Products", "LastModifiedDate");
            DropColumn("dbo.Products", "CreatedDate");
            DropColumn("dbo.Categories", "LastModifiedDate");
            DropColumn("dbo.Categories", "CreatedDate");
            DropColumn("dbo.CodeItems", "LastModifiedDate");
            DropColumn("dbo.CodeItems", "CreatedDate");
            DropColumn("dbo.BaseCodes", "LastModifiedDate");
            DropColumn("dbo.BaseCodes", "CreatedDate");
        }
    }
}
