//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Happy.Scaffolding.MVC.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MvcScaffolderDialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcScaffolderDialogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Happy.Scaffolding.MVC.UI.MvcScaffolderDialogResources", typeof(MvcScaffolderDialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButton_Content {
            get {
                return ResourceManager.GetString("AddButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButton_Content {
            get {
                return ResourceManager.GetString("BackButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton_Content {
            get {
                return ResourceManager.GetString("CancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm and continue..
        /// </summary>
        public static string CheckBox_IsConfirm {
            get {
                return ResourceManager.GetString("CheckBox_IsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller name.
        /// </summary>
        public static string ControllerName {
            get {
                return ResourceManager.GetString("ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data _context class:.
        /// </summary>
        public static string DataContextTypeLabel_Content {
            get {
                return ResourceManager.GetString("DataContextTypeLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master page placeholder ID:.
        /// </summary>
        public static string DesktopContentPlaceholderIdLabel_Content {
            get {
                return ResourceManager.GetString("DesktopContentPlaceholderIdLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master page:.
        /// </summary>
        public static string DesktopViewsLabel_Content {
            get {
                return ResourceManager.GetString("DesktopViewsLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a master page from the list.
        /// </summary>
        public static string Error_DesktopMasterPageRequired {
            get {
                return ResourceManager.GetString("Error_DesktopMasterPageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a model class from the list.
        /// </summary>
        public static string Error_ModelTypeRequired {
            get {
                return ResourceManager.GetString("Error_ModelTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the ID of the placeholder control to place the generated content in.
        /// </summary>
        public static string Error_PlaceholderIdRequired {
            get {
                return ResourceManager.GetString("Error_PlaceholderIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Form Layout Columns  .
        /// </summary>
        public static string FormViewCols {
            get {
                return ResourceManager.GetString("FormViewCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Master-Detail relationship Action and PageView.
        /// </summary>
        public static string GenerateMasterDetailRelationship {
            get {
                return ResourceManager.GetString("GenerateMasterDetailRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate views.
        /// </summary>
        public static string GenerateViews {
            get {
                return ResourceManager.GetString("GenerateViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Leave empty if it is set in Razor _viewstart file).
        /// </summary>
        public static string LeaveEmpty {
            get {
                return ResourceManager.GetString("LeaveEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method name / Store Procedure import function.
        /// </summary>
        public static string MethodNameLabel_Content {
            get {
                return ResourceManager.GetString("MethodNameLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model cla_ss:.
        /// </summary>
        public static string ModelTypeLabel_Content {
            get {
                return ResourceManager.GetString("ModelTypeLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextButton_Content {
            get {
                return ResourceManager.GetString("NextButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over write existing pages.
        /// </summary>
        public static string OverwriteCheckBox_Content {
            get {
                return ResourceManager.GetString("OverwriteCheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program title.
        /// </summary>
        public static string ProgramerNameLabel_Content {
            get {
                return ResourceManager.GetString("ProgramerNameLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference script libraries.
        /// </summary>
        public static string ReferenceScriptLibraries {
            get {
                return ResourceManager.GetString("ReferenceScriptLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add MVC from Store Procedure.
        /// </summary>
        public static string SPScaffolderDialog_Title {
            get {
                return ResourceManager.GetString("SPScaffolderDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query form setting.
        /// </summary>
        public static string SPScaffolderDialog_Title2 {
            get {
                return ResourceManager.GetString("SPScaffolderDialog_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result list column setting.
        /// </summary>
        public static string SPScaffolderDialog_Title3 {
            get {
                return ResourceManager.GetString("SPScaffolderDialog_Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add MVC controller and views for C.R.U.D.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use async controller actions.
        /// </summary>
        public static string UseAsyncControllerActions {
            get {
                return ResourceManager.GetString("UseAsyncControllerActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a layout page.
        /// </summary>
        public static string UseLayoutPage {
            get {
                return ResourceManager.GetString("UseLayoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View prefix.
        /// </summary>
        public static string ViewPrefixLabel_Content {
            get {
                return ResourceManager.GetString("ViewPrefixLabel_Content", resourceCulture);
            }
        }
    }
}
