//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_WebClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKS
    {
        public string ID { get; set; }
        public string BOOKNAME { get; set; }
        public string AUTHOR { get; set; }
        public Nullable<System.DateTime> PUBLISH_UTC { get; set; }
        public Nullable<int> VERSION_NUM { get; set; }
        public Nullable<long> VERSION_NUM2 { get; set; }
        public Nullable<bool> ISOK { get; set; }
        public Nullable<decimal> LIST_PRICE { get; set; }
        public Nullable<double> Discount { get; set; }
    }
}
