//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRP_BS_SEQ
    {
        public string TABLE_NA { get; set; }
        public string PK_YYYY { get; set; }
        public string PK_MM { get; set; }
        public string PK_DD { get; set; }
        public string PK_STR1 { get; set; }
        public Nullable<short> CURRENT_SEQ { get; set; }
        public Nullable<System.DateTime> MOD_UTC { get; set; }
    }
}
