//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRP_BS_TAG
    {
        public string TAG_ID { get; set; }
        public string TAG_TITLE { get; set; }
        public string TAG_COLOR { get; set; }
        public string COMP_NO { get; set; }
        public string DEP_NO { get; set; }
        public string WHE_NO { get; set; }
    }
}
